version: '2'
services:
  php:
    container_name: co2_php_1
    build: ./docker/php
    ports:
     - "81:80"
     - "444:443"
    volumes:
     - .:/var/www/html
     - ./docker/apache:/etc/apache2/sites-enabled:ro
    networks:
     - appnet
  db:
    container_name: co2_db_1
    build: ./docker/postgres
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: co2
      POSTGRES_USER: co2
      POSTGRES_PASSWORD: co2
    volumes:
     - data:/var/lib/postgresql/data
    networks:
     - appnet
volumes:
  data:
    driver: "local"
networks:
  appnet:
    driver: "bridge"
